exports.categories = [
    "Web Development",
    "Mobile Development",
    "Data Science",
    "Machine Learning",
    "Cloud Computing",
    "Cyber Security",
    "Game Development",
    "AI & Deep Learning",
    "Blockchain",
    "DevOps",
    "Software Engineering",
    "Digital Marketing",
    "UI/UX Design",
    "Project Management",
    "Business Analysis",
    "Networking",
    "Database Management",
    "IT Support",
    "Quality Assurance",
    "Data Analysis",
    "Data Engineering",
    "Others",
];
